### ISSUE TITLE
Moving off of haskell.nix

### ISSUE THREAD

**Issue by HariAmoor-professional** [mlabs-haskell/mlabs-tooling.nix#4]
@L-as+team: Would you guys consider moving this repo off of haskell.nix and onto [Horizon](https://gitlab.homotopic.tech/horizon/horizon-platform)? The goal is to get off of the constraint solver used by Stackage/Cabal and move everything to pure Nix, as specified in [the docs](https://horizon-haskell.net).

cc. @locallycompact

**Comment by HariAmoor-professional** [comment]
Really, it'd be [horizon-plutus](https://gitlab.homotopic.tech/horizon/horizon-plutus), but the idea is to do everything with an overlay

**Comment by L-as** [comment]
We'd have to investigate it, not sure it will be possible.

**Comment by HariAmoor-professional** [comment]
Closing for now, might reopen later with investigation on the amount of work needed and expected benefit
