### ISSUE TITLE
missing default in flake outputs

### ISSUE THREAD

**Issue by lemmon-714** [mlabs-haskell/mlabs-tooling.nix#5]
Please add this or add instructions on how to run

**Comment by L-as** [comment]
This is not how this is supposed to be used.

**Comment by lemmon-714** [comment]
How is it supposed to be used?

**Comment by lemmon-714** [comment]
Thank you for asking, mr 714, ser

**Comment by lemmon-714** [comment]
@lemmon-714 just use Agora

@lemmon-714 ok thanks I will do that, thumbs up
